[features]
seeds = false
skip-lint = false
[programs.localnet]
election = "Gn3U9YVqjFmaNnKFBvDX4qaoTum4CBDwJz4KoYH6P4hA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/alexjakubko/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
